import "./globals.css";
import { Providers } from "@/app/[locale]/providers";

import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import Sidebar from "@/components/sidebar/Sidebar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {

  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html dir={`${locale == "en" || locale == "de" ? "ltr" : "rtl"}`} lang={locale}>
      <body>
        <NextIntlClientProvider>
          <Providers>
            <main className="flex h-screen w-full flex-row p-2 gap-4">
              <aside className="w-2/12 h-full max-w-3/12">
                <Sidebar />
              </aside>

              <section className="w-10/12 h-full max-w-9/12 overflow-y-auto">
                {children}
              </section>
            </main>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
